DROP TABLE tbmarcas;
CREATE TABLE tbmarcas (
  Descripcion VARCHAR(20),
  Id AUTOINC NOT NULL, 
  INDEX Id (Id), 
  INDEX Descripcion (Descripcion)
);
INSERT INTO tbmarcas (Descripcion, Id) values ('EDIS BUSCARONS', 2);
INSERT INTO tbmarcas (Descripcion, Id) values ('BETTY MCLELLAN', 3);
INSERT INTO tbmarcas (Descripcion, Id) values ('SAINT GERMAIN', 4);
INSERT INTO tbmarcas (Descripcion, Id) values ('DANIEL M ECHEVERRIA', 5);
INSERT INTO tbmarcas (Descripcion, Id) values ('THICH NHAT HANH', 6);
INSERT INTO tbmarcas (Descripcion, Id) values ('JACK HAWLEY', 7);
INSERT INTO tbmarcas (Descripcion, Id) values ('KHALIL GIBRAN', 8);
INSERT INTO tbmarcas (Descripcion, Id) values ('NILDA MACIAS', 9);
INSERT INTO tbmarcas (Descripcion, Id) values ('ANTON PONCE DE LEON', 10);
INSERT INTO tbmarcas (Descripcion, Id) values ('MARINA BORRUSO', 11);
INSERT INTO tbmarcas (Descripcion, Id) values ('JOSE LUIS BONET', 12);
INSERT INTO tbmarcas (Descripcion, Id) values ('HERMOGENES', 13);
INSERT INTO tbmarcas (Descripcion, Id) values ('ANAEL', 14);
INSERT INTO tbmarcas (Descripcion, Id) values ('DR. H. L. BANSAL', 15);
INSERT INTO tbmarcas (Descripcion, Id) values ('SERGIO MAGAÑA', 16);
INSERT INTO tbmarcas (Descripcion, Id) values ('DON MIGUEL RUIZ', 17);
INSERT INTO tbmarcas (Descripcion, Id) values ('YOGI RAMACHARAKA', 18);
INSERT INTO tbmarcas (Descripcion, Id) values ('GRACIELA PEREZ MARTI', 19);
INSERT INTO tbmarcas (Descripcion, Id) values ('EVANIA REICHERT', 20);
INSERT INTO tbmarcas (Descripcion, Id) values ('DANIEL J. SIEGEL', 21);
INSERT INTO tbmarcas (Descripcion, Id) values ('MAESTRO DEROSE', 22);
INSERT INTO tbmarcas (Descripcion, Id) values ('TSOKNYI RINPOCHE', 23);
INSERT INTO tbmarcas (Descripcion, Id) values ('CARL PICKHARDT', 24);
INSERT INTO tbmarcas (Descripcion, Id) values ('WILLIAM SEARS', 25);
INSERT INTO tbmarcas (Descripcion, Id) values ('IVONNE MENCKEN', 26);
INSERT INTO tbmarcas (Descripcion, Id) values ('GABRIEL SANCHEZ', 27);
INSERT INTO tbmarcas (Descripcion, Id) values ('JOY JOHNSON', 28);
INSERT INTO tbmarcas (Descripcion, Id) values ('ROSEMARY WELLS', 29);
INSERT INTO tbmarcas (Descripcion, Id) values ('GERALD DESKIN', 30);
INSERT INTO tbmarcas (Descripcion, Id) values ('DOLLY N. CAMUSSO', 31);
INSERT INTO tbmarcas (Descripcion, Id) values ('NESTOR BARRON', 32);
INSERT INTO tbmarcas (Descripcion, Id) values ('ANITA MOORJANI', 33);
INSERT INTO tbmarcas (Descripcion, Id) values ('BOKAR RIMPOCHE', 34);
INSERT INTO tbmarcas (Descripcion, Id) values ('DIANA DREXLER', 35);
INSERT INTO tbmarcas (Descripcion, Id) values ('SONIA CAFE - ANA LAP', 36);
INSERT INTO tbmarcas (Descripcion, Id) values ('SAMUEL H. SANDWEISS', 37);
INSERT INTO tbmarcas (Descripcion, Id) values ('BEATRIZ GOLDBERG', 38);
INSERT INTO tbmarcas (Descripcion, Id) values ('PHYLLIS KRYSTAL', 39);
INSERT INTO tbmarcas (Descripcion, Id) values ('ALICIA LOPEZ BLANCO', 40);
INSERT INTO tbmarcas (Descripcion, Id) values ('PERLA PALACCI DE JAC', 41);
INSERT INTO tbmarcas (Descripcion, Id) values ('JAMGON MIPHAM', 42);
INSERT INTO tbmarcas (Descripcion, Id) values ('LAMA KALU RINPOCHE', 43);
INSERT INTO tbmarcas (Descripcion, Id) values ('CARIBE-BETANIA', 44);
INSERT INTO tbmarcas (Descripcion, Id) values ('ETEL SCHULTE', 45);
INSERT INTO tbmarcas (Descripcion, Id) values ('MARTIN ARMANDO', 46);
INSERT INTO tbmarcas (Descripcion, Id) values ('PEDRO ARRIBAS SANCHE', 47);
INSERT INTO tbmarcas (Descripcion, Id) values ('SWAMI PRABHUPADA', 48);
INSERT INTO tbmarcas (Descripcion, Id) values ('LOUISE KEET', 49);
INSERT INTO tbmarcas (Descripcion, Id) values ('DR. DAVID PERLMUTTER', 50);
INSERT INTO tbmarcas (Descripcion, Id) values ('JONNY BOWDEN - STEPH', 51);
INSERT INTO tbmarcas (Descripcion, Id) values ('BERTA ROSA FURER', 52);
INSERT INTO tbmarcas (Descripcion, Id) values ('ANGELITA BIANCULLI', 53);
INSERT INTO tbmarcas (Descripcion, Id) values ('MARTA PEREZ GASPAR', 54);
INSERT INTO tbmarcas (Descripcion, Id) values ('MERCEDES MARTI', 55);
INSERT INTO tbmarcas (Descripcion, Id) values ('ANITA HESSMANN-KOSAR', 56);
INSERT INTO tbmarcas (Descripcion, Id) values ('MARTA RECALDE EUGENI', 57);
INSERT INTO tbmarcas (Descripcion, Id) values ('CALA H.CERVERS', 58);
INSERT INTO tbmarcas (Descripcion, Id) values ('ROBERT ULLMAN', 59);
INSERT INTO tbmarcas (Descripcion, Id) values ('KAYLE GRAY', 325);
INSERT INTO tbmarcas (Descripcion, Id) values ('ANDRAEA BRUNO', 61);
INSERT INTO tbmarcas (Descripcion, Id) values ('ANGELITA BIANCULLI', 62);
INSERT INTO tbmarcas (Descripcion, Id) values ('SRI SATYA SAI BABA', 63);
INSERT INTO tbmarcas (Descripcion, Id) values ('MERCEDES KIRKEL', 64);
INSERT INTO tbmarcas (Descripcion, Id) values ('ROSA RUR', 65);
INSERT INTO tbmarcas (Descripcion, Id) values ('KARINA ZARFINO', 66);
INSERT INTO tbmarcas (Descripcion, Id) values ('YEHUDA BERG', 67);
INSERT INTO tbmarcas (Descripcion, Id) values ('LAURA OLIVO', 68);
INSERT INTO tbmarcas (Descripcion, Id) values ('JUAN EDUARDO CIRLOT', 69);
INSERT INTO tbmarcas (Descripcion, Id) values ('TIFFANY CRUIKSHANK', 70);
INSERT INTO tbmarcas (Descripcion, Id) values ('ALDO LAVAGNINI', 71);
INSERT INTO tbmarcas (Descripcion, Id) values ('EDUARDO R. CALLAEY', 73);
INSERT INTO tbmarcas (Descripcion, Id) values ('JON KABAT-ZINN', 74);
INSERT INTO tbmarcas (Descripcion, Id) values ('PHILIPPA WARING', 75);
INSERT INTO tbmarcas (Descripcion, Id) values ('FRESIA CASTRO MORENO', 76);
INSERT INTO tbmarcas (Descripcion, Id) values ('MIRANDA GRAY', 77);
INSERT INTO tbmarcas (Descripcion, Id) values ('ALBERTO IVERN', 78);
INSERT INTO tbmarcas (Descripcion, Id) values ('PADMA SAMBHAVA', 79);
INSERT INTO tbmarcas (Descripcion, Id) values ('CRISTINA GRAIÑO', 80);
INSERT INTO tbmarcas (Descripcion, Id) values ('ESTEBAN REY', 82);
INSERT INTO tbmarcas (Descripcion, Id) values ('CLAUDIO A. MORAGA FL', 83);
INSERT INTO tbmarcas (Descripcion, Id) values ('CARLOS MOLINERO', 84);
INSERT INTO tbmarcas (Descripcion, Id) values ('JUAN PABLO CAPDEVILA', 85);
INSERT INTO tbmarcas (Descripcion, Id) values ('ALEJANDRO PARRA', 86);
INSERT INTO tbmarcas (Descripcion, Id) values ('GABRIELA BEDUCHAUD', 87);
INSERT INTO tbmarcas (Descripcion, Id) values ('ALICIA LOPEZ BLANCO', 88);
INSERT INTO tbmarcas (Descripcion, Id) values ('HARA', 89);
INSERT INTO tbmarcas (Descripcion, Id) values ('BETINA MARIEL BENSIG', 90);
INSERT INTO tbmarcas (Descripcion, Id) values ('MARIANO WOLFSON', 91);
INSERT INTO tbmarcas (Descripcion, Id) values ('CLAUDIA FEDERICA ZOS', 92);
INSERT INTO tbmarcas (Descripcion, Id) values ('GRACIELA SKILTON', 93);
INSERT INTO tbmarcas (Descripcion, Id) values ('MARTA BEATRIZ CARRAN', 94);
INSERT INTO tbmarcas (Descripcion, Id) values ('CONCEPTO', 95);
INSERT INTO tbmarcas (Descripcion, Id) values ('CLAUDIO MARIA DOMING', 96);
INSERT INTO tbmarcas (Descripcion, Id) values ('DR. M. L. GHAROTE', 97);
INSERT INTO tbmarcas (Descripcion, Id) values ('EILEEN CADDY', 98);
INSERT INTO tbmarcas (Descripcion, Id) values ('MARIO SCHWARZ', 99);
INSERT INTO tbmarcas (Descripcion, Id) values ('KALYANA MALLA', 100);
INSERT INTO tbmarcas (Descripcion, Id) values ('NICOLAR APELT', 101);
INSERT INTO tbmarcas (Descripcion, Id) values ('JODORWSKY', 102);
INSERT INTO tbmarcas (Descripcion, Id) values ('RICARDO BLASCO', 103);
INSERT INTO tbmarcas (Descripcion, Id) values ('DENISEE LINN', 326);
INSERT INTO tbmarcas (Descripcion, Id) values ('OSHO', 105);
INSERT INTO tbmarcas (Descripcion, Id) values ('EMILIO CARRILLO', 106);
INSERT INTO tbmarcas (Descripcion, Id) values ('MANTAK CHIA', 107);
INSERT INTO tbmarcas (Descripcion, Id) values ('BELISARIO ROMAN', 108);
INSERT INTO tbmarcas (Descripcion, Id) values ('RHONDA BYRNE', 109);
INSERT INTO tbmarcas (Descripcion, Id) values ('VIDYMALA BURCH', 110);
INSERT INTO tbmarcas (Descripcion, Id) values ('JAMES R. DOTY', 111);
INSERT INTO tbmarcas (Descripcion, Id) values ('TED J. KAPTCHUK', 112);
INSERT INTO tbmarcas (Descripcion, Id) values ('FABIANA KRAMARZ', 113);
INSERT INTO tbmarcas (Descripcion, Id) values ('GERTRUD HIRSCHI', 114);
INSERT INTO tbmarcas (Descripcion, Id) values ('HARRIET BEINFIELD', 115);
INSERT INTO tbmarcas (Descripcion, Id) values ('PABLO DE LA IGLESIA', 116);
INSERT INTO tbmarcas (Descripcion, Id) values ('LAIN', 117);
INSERT INTO tbmarcas (Descripcion, Id) values ('VATSYAYANA', 118);
INSERT INTO tbmarcas (Descripcion, Id) values ('SONIA CAFE', 119);
INSERT INTO tbmarcas (Descripcion, Id) values ('RABINDRANATH TAGORE', 120);
INSERT INTO tbmarcas (Descripcion, Id) values ('DEVAS', 121);
INSERT INTO tbmarcas (Descripcion, Id) values ('KATHY FRESTON', 122);
INSERT INTO tbmarcas (Descripcion, Id) values ('LILY TAROT', 123);
INSERT INTO tbmarcas (Descripcion, Id) values ('HERBERT KOEBF', 124);
INSERT INTO tbmarcas (Descripcion, Id) values ('JANE STRUTHERS', 125);
INSERT INTO tbmarcas (Descripcion, Id) values ('SARA BARTTLET', 126);
INSERT INTO tbmarcas (Descripcion, Id) values ('CASSANDRA LORIUS', 127);
INSERT INTO tbmarcas (Descripcion, Id) values ('HAZEL RAVEN', 128);
INSERT INTO tbmarcas (Descripcion, Id) values ('JUDY HALL', 129);
INSERT INTO tbmarcas (Descripcion, Id) values ('TERESA MOOREY', 130);
INSERT INTO tbmarcas (Descripcion, Id) values ('HELEN FARMER-KNAWLES', 131);
INSERT INTO tbmarcas (Descripcion, Id) values ('JOEL LEVY', 132);
INSERT INTO tbmarcas (Descripcion, Id) values ('MADONNA GAUDING', 133);
INSERT INTO tbmarcas (Descripcion, Id) values ('ANTHONY J. TAYLOR', 134);
INSERT INTO tbmarcas (Descripcion, Id) values ('AMBIKA WAUTERS', 135);
INSERT INTO tbmarcas (Descripcion, Id) values ('DEREK WALTERS', 136);
INSERT INTO tbmarcas (Descripcion, Id) values ('DEBORA COLAGRECO', 137);
INSERT INTO tbmarcas (Descripcion, Id) values ('ADOLFO PEREZ AGUSTI', 138);
INSERT INTO tbmarcas (Descripcion, Id) values ('MITXEL G. MOHN', 139);
INSERT INTO tbmarcas (Descripcion, Id) values ('HANIA CZAJKOWSKI', 140);
INSERT INTO tbmarcas (Descripcion, Id) values ('NICOLAS CAPO', 141);
INSERT INTO tbmarcas (Descripcion, Id) values ('PETER KELDER', 142);
INSERT INTO tbmarcas (Descripcion, Id) values ('ADAM J. JACKSON', 143);
INSERT INTO tbmarcas (Descripcion, Id) values ('BRIAN WEISS', 144);
INSERT INTO tbmarcas (Descripcion, Id) values ('ERNESTO SPEZZAFUNE', 145);
INSERT INTO tbmarcas (Descripcion, Id) values ('JOHN WATKINS', 146);
INSERT INTO tbmarcas (Descripcion, Id) values ('ALEJANDRA BLUTH SOLA', 147);
INSERT INTO tbmarcas (Descripcion, Id) values ('RUDOLF STEINER', 148);
INSERT INTO tbmarcas (Descripcion, Id) values ('GLORIA MORAN', 149);
INSERT INTO tbmarcas (Descripcion, Id) values ('CAROLINA CAMPOS', 150);
INSERT INTO tbmarcas (Descripcion, Id) values ('ROBERT ELLSBERG', 151);
INSERT INTO tbmarcas (Descripcion, Id) values ('EVA WHITE', 152);
INSERT INTO tbmarcas (Descripcion, Id) values ('LOUISE L. HAY', 153);
INSERT INTO tbmarcas (Descripcion, Id) values ('MICHAEL DAWSON', 154);
INSERT INTO tbmarcas (Descripcion, Id) values ('SANDY SENES', 155);
INSERT INTO tbmarcas (Descripcion, Id) values ('AROMANZA', 156);
INSERT INTO tbmarcas (Descripcion, Id) values ('MICHAEL HARNER', 157);
INSERT INTO tbmarcas (Descripcion, Id) values ('ALEJANDRO LODI', 158);
INSERT INTO tbmarcas (Descripcion, Id) values ('PAUL BRUNTON', 159);
INSERT INTO tbmarcas (Descripcion, Id) values ('MARIA ALVAREZ GARRID', 160);
INSERT INTO tbmarcas (Descripcion, Id) values ('J L MOLINA MILLAN', 161);
INSERT INTO tbmarcas (Descripcion, Id) values ('ENRIC CORBERA', 162);
INSERT INTO tbmarcas (Descripcion, Id) values ('BRENDA MALLON', 163);
INSERT INTO tbmarcas (Descripcion, Id) values ('ANA LIA RIOS', 164);
INSERT INTO tbmarcas (Descripcion, Id) values ('BRIGITTE CHAMPERTIER', 165);
INSERT INTO tbmarcas (Descripcion, Id) values ('TITO MACIA', 166);
INSERT INTO tbmarcas (Descripcion, Id) values ('EUGENIO CARUTTI', 167);
INSERT INTO tbmarcas (Descripcion, Id) values ('MARIA ETCHEVERRY BON', 168);
INSERT INTO tbmarcas (Descripcion, Id) values ('JUAN ESTADELLA', 169);
INSERT INTO tbmarcas (Descripcion, Id) values ('CLAUDIA AZICRI', 170);
INSERT INTO tbmarcas (Descripcion, Id) values ('LILI BOSNIC', 171);
INSERT INTO tbmarcas (Descripcion, Id) values ('MOICA CHACON', 172);
INSERT INTO tbmarcas (Descripcion, Id) values ('JOSEPH BENNER', 173);
INSERT INTO tbmarcas (Descripcion, Id) values ('JOSEFINA LLARGUES', 174);
INSERT INTO tbmarcas (Descripcion, Id) values ('ELIZABETH CLARE PROP', 176);
INSERT INTO tbmarcas (Descripcion, Id) values ('MILAGRO E. CARBAJAL', 177);
INSERT INTO tbmarcas (Descripcion, Id) values ('OMAR RAMAN', 178);
INSERT INTO tbmarcas (Descripcion, Id) values ('LUCILE GARNIER MALET', 179);
INSERT INTO tbmarcas (Descripcion, Id) values ('KEN WILBER', 180);
INSERT INTO tbmarcas (Descripcion, Id) values ('LAURA PODIO', 181);
INSERT INTO tbmarcas (Descripcion, Id) values ('MARTA ROT', 182);
INSERT INTO tbmarcas (Descripcion, Id) values ('ABEL RAUL BROZZI', 183);
INSERT INTO tbmarcas (Descripcion, Id) values ('LINDA RAVENXCROFT', 184);
INSERT INTO tbmarcas (Descripcion, Id) values ('DOREEN VIRTUE', 185);
INSERT INTO tbmarcas (Descripcion, Id) values ('DEBBIE MALONE', 186);
INSERT INTO tbmarcas (Descripcion, Id) values ('MATT HUGHES', 187);
INSERT INTO tbmarcas (Descripcion, Id) values ('LUCY CAVENDISH', 188);
INSERT INTO tbmarcas (Descripcion, Id) values ('COLETTE BARON-REID', 189);
INSERT INTO tbmarcas (Descripcion, Id) values ('OSWALD WIRTH', 190);
INSERT INTO tbmarcas (Descripcion, Id) values ('TONI CARMINE SALERNO', 191);
INSERT INTO tbmarcas (Descripcion, Id) values ('PATRICIA KACHUK', 192);
INSERT INTO tbmarcas (Descripcion, Id) values ('LOAN MIEGE', 193);
INSERT INTO tbmarcas (Descripcion, Id) values ('JULI PERADEJORDI', 194);
INSERT INTO tbmarcas (Descripcion, Id) values ('JOHN MATTHEWS', 195);
INSERT INTO tbmarcas (Descripcion, Id) values ('GRACIELA IRIONDO', 196);
INSERT INTO tbmarcas (Descripcion, Id) values ('AQUILES KOSTAS', 197);
INSERT INTO tbmarcas (Descripcion, Id) values ('CAROLINE SMITH', 198);
INSERT INTO tbmarcas (Descripcion, Id) values ('KIMBERLY MAROONEY', 199);
INSERT INTO tbmarcas (Descripcion, Id) values ('BIANCA LUNA', 200);
INSERT INTO tbmarcas (Descripcion, Id) values ('LAURA TUAN', 201);
INSERT INTO tbmarcas (Descripcion, Id) values ('CONNY MENDEZ', 202);
INSERT INTO tbmarcas (Descripcion, Id) values ('MIHALY CSIKSZENTMIGH', 203);
INSERT INTO tbmarcas (Descripcion, Id) values ('WILLIAM W.ATKINSON', 204);
INSERT INTO tbmarcas (Descripcion, Id) values ('MATTHIEU RICARD', 211);
INSERT INTO tbmarcas (Descripcion, Id) values ('LUCILE Y JEAN-PIERRE', 206);
INSERT INTO tbmarcas (Descripcion, Id) values ('GABRIELA ARIAS URIBU', 207);
INSERT INTO tbmarcas (Descripcion, Id) values ('GUSTAVO ANDRES ROCCO', 208);
INSERT INTO tbmarcas (Descripcion, Id) values ('ANA MARIA CARBALLO', 210);
INSERT INTO tbmarcas (Descripcion, Id) values ('HISPANO EUROPEA', 212);
INSERT INTO tbmarcas (Descripcion, Id) values ('CECELIA AHERN', 213);
INSERT INTO tbmarcas (Descripcion, Id) values ('ADA ALBRECHT', 215);
INSERT INTO tbmarcas (Descripcion, Id) values ('GUDRUN BURKHARD', 216);
INSERT INTO tbmarcas (Descripcion, Id) values ('PARAMAHANSA YOGANAND', 218);
INSERT INTO tbmarcas (Descripcion, Id) values ('MARY T. BROWNE', 219);
INSERT INTO tbmarcas (Descripcion, Id) values ('MYRTA BARVIE', 220);
INSERT INTO tbmarcas (Descripcion, Id) values ('GIOVANNA LAKSHMI', 221);
INSERT INTO tbmarcas (Descripcion, Id) values ('WALTER SOUSA', 222);
INSERT INTO tbmarcas (Descripcion, Id) values ('NATTY PETROSINO', 223);
INSERT INTO tbmarcas (Descripcion, Id) values ('MARIO MAZZOLENI', 224);
INSERT INTO tbmarcas (Descripcion, Id) values ('ANA GAMBACCINI', 225);
INSERT INTO tbmarcas (Descripcion, Id) values ('KOSEN THIBAUT', 226);
INSERT INTO tbmarcas (Descripcion, Id) values ('RICARDO E. LEVERATTO', 227);
INSERT INTO tbmarcas (Descripcion, Id) values ('JOSEPH CARTER', 228);
INSERT INTO tbmarcas (Descripcion, Id) values ('ADRIANA ZUFRIATEGUI', 229);
INSERT INTO tbmarcas (Descripcion, Id) values ('PAULA MORENO', 230);
INSERT INTO tbmarcas (Descripcion, Id) values ('DEVA PREMAL & MITEN', 231);
INSERT INTO tbmarcas (Descripcion, Id) values ('MIKE DOOLEY ', 232);
INSERT INTO tbmarcas (Descripcion, Id) values ('SRI SRI RAVI SHANKAR', 233);
INSERT INTO tbmarcas (Descripcion, Id) values ('BERT HELLINGER', 234);
INSERT INTO tbmarcas (Descripcion, Id) values ('C. W. LEADBEATER', 235);
INSERT INTO tbmarcas (Descripcion, Id) values ('IVAN KIROV', 237);
INSERT INTO tbmarcas (Descripcion, Id) values ('ELIPHAS LEVI', 238);
INSERT INTO tbmarcas (Descripcion, Id) values ('LAM KAM CHUEN', 239);
INSERT INTO tbmarcas (Descripcion, Id) values ('KIRSTEN M.LAGATREE', 240);
INSERT INTO tbmarcas (Descripcion, Id) values ('RICHARD BANDLER', 241);
INSERT INTO tbmarcas (Descripcion, Id) values ('ISABELA HERRANZ', 242);
INSERT INTO tbmarcas (Descripcion, Id) values ('RAMIRO ELEAZAR LOREN', 243);
INSERT INTO tbmarcas (Descripcion, Id) values ('SEBASTIAN VAZQUEZ', 244);
INSERT INTO tbmarcas (Descripcion, Id) values ('JOSE SBARRA', 245);
INSERT INTO tbmarcas (Descripcion, Id) values ('GISLAINE MARIA D ASS', 246);
INSERT INTO tbmarcas (Descripcion, Id) values ('GRACIELA MORESCHI', 247);
INSERT INTO tbmarcas (Descripcion, Id) values ('JOSE MARIA CAMPOS', 248);
INSERT INTO tbmarcas (Descripcion, Id) values ('NOSTRADAMUS', 250);
INSERT INTO tbmarcas (Descripcion, Id) values ('BARBARA MARCINIAK', 251);
INSERT INTO tbmarcas (Descripcion, Id) values ('SIRANUS SVEN VON STA', 252);
INSERT INTO tbmarcas (Descripcion, Id) values ('LUCIA OLIVEIRA', 253);
INSERT INTO tbmarcas (Descripcion, Id) values ('DAVID EARL PLATTS', 254);
INSERT INTO tbmarcas (Descripcion, Id) values ('EUGENE CANSELIET', 255);
INSERT INTO tbmarcas (Descripcion, Id) values ('EDWARD BACH', 256);
INSERT INTO tbmarcas (Descripcion, Id) values ('ARMANDO CARRANZA', 257);
INSERT INTO tbmarcas (Descripcion, Id) values ('EDUARDO H. GRECCO', 258);
INSERT INTO tbmarcas (Descripcion, Id) values ('MECHTHILD SCHEFFER', 259);
INSERT INTO tbmarcas (Descripcion, Id) values ('ANA VALBUENA', 260);
INSERT INTO tbmarcas (Descripcion, Id) values ('FRANCO ROSSOMANDO', 261);
INSERT INTO tbmarcas (Descripcion, Id) values ('STEFAN BALL', 262);
INSERT INTO tbmarcas (Descripcion, Id) values ('ROLAND SANANES', 263);
INSERT INTO tbmarcas (Descripcion, Id) values ('TUNG KUO TSAO', 264);
INSERT INTO tbmarcas (Descripcion, Id) values ('GAYLE FORMAN', 265);
INSERT INTO tbmarcas (Descripcion, Id) values ('JEAN-PAUL NOWAK', 266);
INSERT INTO tbmarcas (Descripcion, Id) values ('ROSANA PINERA', 267);
INSERT INTO tbmarcas (Descripcion, Id) values ('KAREN BERG', 268);
INSERT INTO tbmarcas (Descripcion, Id) values ('MIRANDA GRAY', 269);
INSERT INTO tbmarcas (Descripcion, Id) values ('ALEJANDRO GORENSTEIN', 270);
INSERT INTO tbmarcas (Descripcion, Id) values ('PEDRO ENGEL', 271);
INSERT INTO tbmarcas (Descripcion, Id) values ('JOSE J. DE OLANETA', 272);
INSERT INTO tbmarcas (Descripcion, Id) values ('PHILIPPE-GASTON BESS', 273);
INSERT INTO tbmarcas (Descripcion, Id) values ('FRANCISCO CANDIDO XA', 274);
INSERT INTO tbmarcas (Descripcion, Id) values ('GERMAN W. CLARK', 275);
INSERT INTO tbmarcas (Descripcion, Id) values ('ERNESTO JOSE MASIN', 276);
INSERT INTO tbmarcas (Descripcion, Id) values ('ELIZABETH HAITCH Y S', 277);
INSERT INTO tbmarcas (Descripcion, Id) values ('IONA PURTI', 278);
INSERT INTO tbmarcas (Descripcion, Id) values ('RICARDO DOKYU', 279);
INSERT INTO tbmarcas (Descripcion, Id) values ('BARBARA ESPECHE', 280);
INSERT INTO tbmarcas (Descripcion, Id) values ('LORNA BYRBE', 281);
INSERT INTO tbmarcas (Descripcion, Id) values ('GOLOKA FRAGANCE', 283);
INSERT INTO tbmarcas (Descripcion, Id) values ('GOLOKA FIT', 284);
INSERT INTO tbmarcas (Descripcion, Id) values ('GOLOKA AROMATHERAPY', 285);
INSERT INTO tbmarcas (Descripcion, Id) values ('GOLOKA NATURE', 286);
INSERT INTO tbmarcas (Descripcion, Id) values ('GOLOKA XX', 287);
INSERT INTO tbmarcas (Descripcion, Id) values ('GOLOKA ORGANICA', 289);
INSERT INTO tbmarcas (Descripcion, Id) values ('GOLOKA REIKI', 290);
INSERT INTO tbmarcas (Descripcion, Id) values ('MURRAY & LANMAN', 291);
INSERT INTO tbmarcas (Descripcion, Id) values ('BALAJI', 292);
INSERT INTO tbmarcas (Descripcion, Id) values ('SATYA', 293);
INSERT INTO tbmarcas (Descripcion, Id) values ('SREE VARI', 294);
INSERT INTO tbmarcas (Descripcion, Id) values ('VIVANTA', 295);
INSERT INTO tbmarcas (Descripcion, Id) values ('PARIMAL', 296);
INSERT INTO tbmarcas (Descripcion, Id) values ('LIBERTY', 297);
INSERT INTO tbmarcas (Descripcion, Id) values ('MASALA INDIA', 298);
INSERT INTO tbmarcas (Descripcion, Id) values ('OM SAI KRISHNA', 299);
INSERT INTO tbmarcas (Descripcion, Id) values ('ILUMINARTE INDIA', 300);
INSERT INTO tbmarcas (Descripcion, Id) values ('HEM', 301);
INSERT INTO tbmarcas (Descripcion, Id) values ('ULLAS', 303);
INSERT INTO tbmarcas (Descripcion, Id) values ('GOVINDA', 304);
INSERT INTO tbmarcas (Descripcion, Id) values ('SAGRADA MADRE', 305);
INSERT INTO tbmarcas (Descripcion, Id) values ('SIN STOCK', 306);
INSERT INTO tbmarcas (Descripcion, Id) values ('MAGDELINA MESSINA', 307);
INSERT INTO tbmarcas (Descripcion, Id) values ('TERESA PINANA VIVES', 308);
INSERT INTO tbmarcas (Descripcion, Id) values ('SANDRA MERAKI', 309);
INSERT INTO tbmarcas (Descripcion, Id) values ('SAHUMO NATIVO', 310);
INSERT INTO tbmarcas (Descripcion, Id) values ('EN STOCK', 311);
INSERT INTO tbmarcas (Descripcion, Id) values ('VILLOLDO', 312);
INSERT INTO tbmarcas (Descripcion, Id) values ('SAHARA ROSE', 313);
INSERT INTO tbmarcas (Descripcion, Id) values ('MARIO MONTANO', 314);
INSERT INTO tbmarcas (Descripcion, Id) values ('ALEJANDRO JODOROWSKY', 315);
INSERT INTO tbmarcas (Descripcion, Id) values ('ALANA FAIRCHILD', 317);
INSERT INTO tbmarcas (Descripcion, Id) values ('CAROLINE MYSS', 318);
INSERT INTO tbmarcas (Descripcion, Id) values ('SONIA CHOQUETTE', 319);
INSERT INTO tbmarcas (Descripcion, Id) values ('SHARON ANNE KLINGLER', 320);
INSERT INTO tbmarcas (Descripcion, Id) values ('MEGAN WATTERSON', 321);
INSERT INTO tbmarcas (Descripcion, Id) values ('LISE BARTOLI', 322);
INSERT INTO tbmarcas (Descripcion, Id) values ('REBECCA CAMPBELL', 323);
INSERT INTO tbmarcas (Descripcion, Id) values ('KYLE GRAY', 324);
INSERT INTO tbmarcas (Descripcion, Id) values ('ISABELLE CERF', 327);
INSERT INTO tbmarcas (Descripcion, Id) values ('FLAVIA KATE PETERS', 328);
INSERT INTO tbmarcas (Descripcion, Id) values ('KAY STOPFORTH', 330);
INSERT INTO tbmarcas (Descripcion, Id) values ('GRANT VIRTUE', 331);
INSERT INTO tbmarcas (Descripcion, Id) values ('BARBARA MOORE', 332);
INSERT INTO tbmarcas (Descripcion, Id) values ('ROBERT Y HOLLIE HOLD', 333);
INSERT INTO tbmarcas (Descripcion, Id) values ('ROSE INSERRA', 334);
INSERT INTO tbmarcas (Descripcion, Id) values ('ARTHUR E. WAITE', 336);
INSERT INTO tbmarcas (Descripcion, Id) values ('JAMES VAN PRAAGH', 337);
INSERT INTO tbmarcas (Descripcion, Id) values ('TORI HARTMAN', 338);
INSERT INTO tbmarcas (Descripcion, Id) values ('STACEY DEMARCO', 339);
INSERT INTO tbmarcas (Descripcion, Id) values ('KARINE MALENFANT', 340);
INSERT INTO tbmarcas (Descripcion, Id) values ('PEMA CHODRON', 341);
INSERT INTO tbmarcas (Descripcion, Id) values ('CHATRIYA HRMH ARNVIB', 342);
INSERT INTO tbmarcas (Descripcion, Id) values ('KELLY SULLIVAN WALDE', 343);
INSERT INTO tbmarcas (Descripcion, Id) values ('AITOR SARAITA', 344);
INSERT INTO tbmarcas (Descripcion, Id) values ('PAUL HUSON', 345);
INSERT INTO tbmarcas (Descripcion, Id) values ('MARKUS SCHIRNER', 346);
INSERT INTO tbmarcas (Descripcion, Id) values ('DOROTHY LEWIS', 347);
INSERT INTO tbmarcas (Descripcion, Id) values ('ALICIA ALVAREZ', 348);
INSERT INTO tbmarcas (Descripcion, Id) values ('PABLITO MARTIN', 349);
INSERT INTO tbmarcas (Descripcion, Id) values ('BEATRIZ LEVERATTO', 350);
INSERT INTO tbmarcas (Descripcion, Id) values ('MIMY CIROCCO', 351);
INSERT INTO tbmarcas (Descripcion, Id) values ('RADLEIGH VALENTINE', 352);
INSERT INTO tbmarcas (Descripcion, Id) values ('JOHANNES FIEBIG', 353);
INSERT INTO tbmarcas (Descripcion, Id) values ('DR. JEAN-JACQUES', 354);
INSERT INTO tbmarcas (Descripcion, Id) values ('DRA NADIA GIRAUDO', 355);
INSERT INTO tbmarcas (Descripcion, Id) values ('ENRIQUE BOURON', 356);
INSERT INTO tbmarcas (Descripcion, Id) values ('ELOY R. DUMON', 357);
INSERT INTO tbmarcas (Descripcion, Id) values ('RIMPOCHE SOG', 358);
INSERT INTO tbmarcas (Descripcion, Id) values ('CRISTINA HYLAND', 359);
INSERT INTO tbmarcas (Descripcion, Id) values ('RICARDO LUIS GERULA', 360);
INSERT INTO tbmarcas (Descripcion, Id) values ('SUSANA TESOURO', 362);
INSERT INTO tbmarcas (Descripcion, Id) values ('DRA. INES L. GROBA', 363);
INSERT INTO tbmarcas (Descripcion, Id) values ('MAXIMILIANO PERALTA', 364);
INSERT INTO tbmarcas (Descripcion, Id) values ('JORGE L. GONDRA', 365);
INSERT INTO tbmarcas (Descripcion, Id) values ('NESTOR CESARINI', 366);
INSERT INTO tbmarcas (Descripcion, Id) values ('CARLOS ROMANO', 367);
INSERT INTO tbmarcas (Descripcion, Id) values ('STEPHEN ARROYO', 368);
INSERT INTO tbmarcas (Descripcion, Id) values ('B. K. JAYANTI', 369);
INSERT INTO tbmarcas (Descripcion, Id) values ('LAO TSE', 370);
INSERT INTO tbmarcas (Descripcion, Id) values ('JAZMIN GULI', 371);
INSERT INTO tbmarcas (Descripcion, Id) values ('PARACELSO', 372);
INSERT INTO tbmarcas (Descripcion, Id) values ('VIVIANA BERGMAN', 373);
INSERT INTO tbmarcas (Descripcion, Id) values ('W. Y. EVANS-WENTZ', 374);
INSERT INTO tbmarcas (Descripcion, Id) values ('SIRI DATTA', 375);
INSERT INTO tbmarcas (Descripcion, Id) values ('SATYA SINGH', 376);
INSERT INTO tbmarcas (Descripcion, Id) values ('FRANZ HARTMANN', 377);
INSERT INTO tbmarcas (Descripcion, Id) values ('DR. A. LIFCHITZ', 378);
INSERT INTO tbmarcas (Descripcion, Id) values ('SWAMI VIVEKANANDA', 379);
INSERT INTO tbmarcas (Descripcion, Id) values ('MARIA VERONICA RIERA', 380);
INSERT INTO tbmarcas (Descripcion, Id) values ('SANDRA AISENBERG', 381);
INSERT INTO tbmarcas (Descripcion, Id) values ('PETER CZANYO', 382);
INSERT INTO tbmarcas (Descripcion, Id) values (',', 383);
INSERT INTO tbmarcas (Descripcion, Id) values ('     ', 384);

